### PR TITLE
Use @angular/cli library build tooling for library build process 

### PR DESCRIPTION
**Pull request by benelliott**
This simplifies the library build process, making it easier to contribute and to update to new versions of Angular over time.

Tested via existing unit tests, and by using `npm link` to import the library into an existing consumer app of Spectator. But it may need some minor changes to the CI config.

### CODE REVIEW

**Comment by benelliott** [comment]
1. Yep - it is exported via a triple-slash directive in `public_api.ts`:

https://github.com/NetanelBasal/spectator/pull/50/files#diff-00c2321e16a255c3f3a1555401ffd850R1

I didn't get any type errors when using the custom matchers in my example project.

2. Sure - anything in particular you would like me to add? Do you want it to be part of this PR or a separate one?

**Comment by benelliott** [comment]
Btw - I don't seem to be able to change anything on Semaphore for the moment. This is me: https://semaphoreci.com/users/benelliott/

**Comment by NetanelBasal** [comment]
Check your email. You should get an invitation. 

It can be a part of this PR. Just information about how to contribute to this project. You can see an example [here](https://github.com/datorama/akita/blob/master/CONTRIBUTING.md).

**Comment by benelliott** [comment]
Thanks, will do. I can view the CI now but it looks like I can't change build settings for individual branches - is it OK if I reconfigure it to work with this PR? I will maybe do it by creating a new job and keeping the old one

**Comment by NetanelBasal** [comment]
Sure, if you need me to do it on master, let me know.

**Comment by NetanelBasal** [comment]
Great work, man! Do you have success with the master branch in CI?

**Comment by NetanelBasal** [comment]
05 11 2018 14:28:20.579:WARN [karma]: Test suite was empty.

Finished in 0.002 secs / 0 secs @ 14:28:20 GMT+0000 (UTC)

SUMMARY:
✔ 0 tests completed

**Comment by benelliott** [comment]
Sorry, what do you mean by the master branch? I don't think that CI server will allow per-branch configurations so I reconfigured it for the new branch. This will mean that the older branches stop building properly.

The test suite for the library itself is empty but there are actually two test suites being run: one for the library and one for the demo app (which still has the old tests).

**Comment by NetanelBasal** [comment]
Ok, you can merge and publish. Thanks a lot for the great work.

**Comment by benelliott** [comment]
Thanks!

**Comment by benelliott** [comment]
@NetanelBasal I've published it under 2.0.7-alpha.1 (because I didn't want to bump people to a broken version!). If you are happy with it, let me know what tag you would like me to release it under - not sure if it should be a major/minor/patch update because the angular peer dep version has changed?

Anyway, I've tested the alpha version on a project and it seems happy.

**Comment by benelliott** [comment]
Published 2.1.0 :)

**Pull request merged**
