### PR TITLE
refactor: repo restructure and dependency upgrades

### PR DESCRIPTION
**Pull request by dirkluijk**
So, I decided not to work on the unit tests but first focus on improving the repo structure and configuration.

In this PR:

* [X] rebased the repo structure on new Angular library project
* [X] moved tests from Angular app to Angular lib (better for coverage, etc)
* [X] removed e2e directory
* [X] changed structure of Jasmine + Jest test suites a bit
* [X] dependency cleanup
* [X] stricter linting + tsconfig settings (+ applied fixes to source) -> feel free to discuss any rules
* [X] Angular 8 upgrade
* [X] upgrade to Karma 4 + Jasmine 3, had to do small fixes for that
* [X] Upgraded other deps

### CODE REVIEW

**Comment by dirkluijk** [comment]
I see that Node 10.9 is required for Angular 8, can you update the Semaphore CI job?

**Comment by NetanelBasal** [comment]
Done

**Comment by NetanelBasal** [comment]
It's hard to see the big picture in the PR, so I will review it after you merge.

**Comment by dirkluijk** [comment]
No problem! I'll do some additional tests and merge it asap.

**Comment by dirkluijk** [comment]
Fun fact: I did a small test on an existing Spectator v3 project. As far as I can tell, the only breaking change was:

```
const spectator = createComponent({}, false);
```
to
```
const spectator = createComponent({ detectChanges: false });
```
Can we write a schematic for that?

**Pull request merged**
