### PR TITLE
feat(spectator): optimize compilation with ng-bullet

### PR DESCRIPTION
**Pull request by dirkluijk**
Closes https://github.com/NetanelBasal/spectator/issues/89.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Available with `npm i @netbasal/spectator@next`. LMK. Thanks.

**Comment by dirkluijk** [comment]
Nice @NetanelBasal, thanks. Will get back with the results.

**Comment by dirkluijk** [comment]
Just moved `ng-bullet` from `devDependencies` to `dependencies`.

However, I can't measure any difference anymore. See #89.

**Comment by magikMaker** [comment]
Any news on this?

**Comment by MartinNuc** [comment]
Tested on our project. Basically just installed `@netbasal/spectator@beta` and `ng-bullet`. We have only 300 tests. Tried 10 rounds:

without `ng-bullet`:

> Finished in 14.337 secs / 13.029 secs @ 14:06:24 GMT+0200 (CEST)
> Finished in 15.441 secs / 14.32 secs @ 14:07:50 GMT+0200 (CEST)
> Finished in 13.698 secs / 12.552 secs @ 14:08:41 GMT+0200 (CEST)
> Finished in 14.897 secs / 13.619 secs @ 14:09:30 GMT+0200 (CEST)
> Finished in 13.488 secs / 12.28 secs @ 14:10:22 GMT+0200 (CEST)
> Finished in 15.244 secs / 13.903 secs @ 14:11:18 GMT+0200 (CEST)
> Finished in 14.334 secs / 13.021 secs @ 14:12:08 GMT+0200 (CEST)
> Finished in 14.711 secs / 13.513 secs @ 14:13:10 GMT+0200 (CEST)
> Finished in 13.968 secs / 12.722 secs @ 14:14:04 GMT+0200 (CEST)
> Finished in 15.188 secs / 13.882 secs @ 14:14:59 GMT+0200 (CEST)

with `ng-bullet`:
> Finished in 14.95 secs / 13.686 secs @ 14:18:27 GMT+0200 (CEST)
> Finished in 14.161 secs / 12.965 secs @ 14:19:25 GMT+0200 (CEST)
> Finished in 14.161 secs / 12.965 secs @ 14:19:25 GMT+0200 (CEST)
> Finished in 13.497 secs / 12.345 secs @ 14:21:52 GMT+0200 (CEST)
> Finished in 15.475 secs / 14.199 secs @ 14:23:10 GMT+0200 (CEST)
> Finished in 14.156 secs / 12.944 secs @ 14:24:25 GMT+0200 (CEST)
> Finished in 13.98 secs / 12.709 secs @ 14:25:19 GMT+0200 (CEST)
> Finished in 13.372 secs / 12.249 secs @ 14:26:16 GMT+0200 (CEST)
> Finished in 15.611 secs / 14.243 secs @ 14:27:08 GMT+0200 (CEST)
> Finished in 13.941 secs / 12.737 secs @ 14:28:06 GMT+0200 (CEST)

Looks to me pretty much same. Do you guys see any improvement? Maybe we dont have enough of tests to see the difference.

**Comment by LayZeeDK** [comment]
@MartinNuc Do you have component templates and stylesheets in separate files or inline?

**Comment by MartinNuc** [comment]
Separated.

**Comment by LayZeeDK** [comment]
That's odd. 300 component tests should be more than enough to spot a difference.

**Comment by MartinNuc** [comment]
Those include also services tests. There are less component tests. Can you make same benchmark like I did on your projects?

**Comment by LayZeeDK** [comment]
I only have a very small project using Spectator 😕

**Comment by MartinNuc** [comment]
Well at least it didn't get worse :-) So I guess let's merge it?

**Comment by LayZeeDK** [comment]
I'm not sure it's a good dependency to add to this library. Ivy should make template processing in tests faster.

If we depend on `ng-bullet` and it isn't compatible with some version of Angular, we would have to wait for it to support that version of Angular before we could release a version of Spectator to support the Angular version in question.

`ng-bullet` is a hack of the Angular testing libraries. Ivy will bring a non-hacky solution for faster tests.

**Comment by dirkluijk** [comment]
Agreed

**Pull request closed without merging**
