### PR TITLE
feat(spectator): additional query capabilities

### PR DESCRIPTION
**Pull request by dirkluijk**
Proposal for https://github.com/NetanelBasal/spectator/issues/142.

### CODE REVIEW

**Comment by NetanelBasal** [comment]
LGTM

**Comment by dirkluijk** [comment]
Build has been fixed.

**Comment by dirkluijk** [comment]
I'll merge this one. @NetanelBasal Can you make a release? 😄

**Comment by NetanelBasal** [comment]
Can you give me your npm user, I want to provide you with permissions.

**Comment by dirkluijk** [comment]
@NetanelBasal it's **dirkluijk**. Thanks!

**Pull request merged**
